codes: ['001763', '000176', '050025', '006479']
look_back: 180

robust_markowitz_robust:
    kappa: 1.0
    delta: 0.1
    lambda: 0.5

mean_downside_risk:
    lambda: 0.5
    alpha: 2

mean_cvar:
    lambda: 0.5
    alpha: 0.95

method: 'mean_cvar'