codes: ['002943', '006479', '000006', '050025']
look_back: 60

robust_markowitz_robust:
    kappa: 1.0
    delta: 0.1
    lambda: 0.5

mean_downside_risk:
    lambda: 0.5
    alpha: 2

mean_cvar:
    lambda: 0.5
    alpha: 0.98

mean_max_draw_down:
    c: 0.2

mean_avg_draw_down:
    c: 0.2

mean_cdar:
    c: 0.1
    alpha: 0.95

method: 'most_diversified'